### ISSUE TITLE
Composer Issues

### ISSUE THREAD

**Issue by oleteacher** [mohamed-samir907/json-db#8]
Hello. I run in folder:

composer require samirzz/jldb

But get:

```
  [InvalidArgumentException]
  Could not find a version of package samirzz/jldb matching your minimum-stability (stable). Require it with an expli  cit version constraint allowing its desired stability.
```

Have never seen that error before in composer. What am I doing wrong?

Thank you!

**Comment by mohamed-samir907** [comment]
@oleteacher Hello,
Try `composer require samirzz/jldb:dev-master`

**Comment by oleteacher** [comment]
I should have though of that, but just pasted in your install instructions instead:

composer require samirzz/jldb

Worked fine, thank you for getting me fixed.
